public interface TreeType {
    String IDENTIFIER = "Py:IDENTIFIER";
    String TARGET_EXPRESSION = "Py:TARGET_EXPRESSION";
    String PSI_WHITE_SPACE = "PsiWhiteSpace";
    String ANNOTATION ="Py:ANNOTATION";
    String NAMED_PARAMETER ="Py:NAMED_PARAMETER";
    String REFERENCE_EXPRESSION ="Py:REFERENCE_EXPRESSION";
    String FUNCTION_DECLARATION ="Py:FUNCTION_DECLARATION";
    String PARAMETER_LIST ="Py:PARAMETER_LIST";
}
